-- CreateTable
CREATE TABLE "Vehicle" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "ownerId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "make" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "plateNumber" TEXT NOT NULL,
    "transmission" TEXT,
    "fuelType" TEXT,
    "locationLat" REAL,
    "locationLng" REAL,
    "locationDistrict" TEXT,
    "pricingMode" TEXT NOT NULL,
    "pricePerDay" REAL,
    "kmIncludedPerDay" INTEGER,
    "pricePerExtraKm" REAL,
    "fuelPolicy" TEXT,
    "chauffeurIncluded" BOOLEAN,
    "decorationAvailable" BOOLEAN,
    "minimumBookingHours" INTEGER,
    "helmetsIncluded" INTEGER,
    "engineCC" INTEGER,
    "requiredLicenseClass" TEXT,
    "minimumRiderAge" INTEGER,
    "revenueLicenseDocUrl" TEXT,
    "vehicleRegistrationDocUrl" TEXT,
    "insuranceDocUrl" TEXT,
    "insuranceExpiryDate" DATETIME,
    "insuranceType" TEXT,
    "baselinePhotosJson" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING_REVIEW',
    "averageRating" REAL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Vehicle_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
